
// POST http://localhost:3000/employes
// Content-Type: application/json

//{
//"nom": "Coltrane",
//"prenom": "John"
//}


POST http://localhost:3000/animal
Content-Type: application/json

{
  "nom": "Maurice",
  "age": 5,
  "race": "Labrador"
}


