
// POST http://localhost:3000/employes
// Content-Type: application/json

//{
//"nom": "Coltrane",
//"prenom": "John"
//}


POST http://localhost:3000/animals
Content-Type: application/json

{
  "nom": "Michel",
  "espece": "652517932794cb7e1df4b029",
  "employes": []

}



